### ISSUE TITLE
Can't load `htdemucs_ft.yaml`

### ISSUE THREAD

**Issue by piwawa** [karaokenerds/python-audio-separator#67]
```
$ audio-separator audio_example.mp3 --model_filename "htdemucs_ft.yaml"

2024-05-01 23:51:49.207 - INFO - cli - Separator version 0.16.6 beginning with input file: audio_example.mp3
2024-05-01 23:51:49.208 - INFO - separator - Separator version 0.16.6 instantiating with output_dir: None, output_format: FLAC
2024-05-01 23:51:49.208 - INFO - separator - Operating System: Linux #1 SMP PREEMPT Fri Mar 1 16:56:12 UTC 2024
2024-05-01 23:51:49.210 - INFO - separator - System: Linux Node: zernithos Release: 5.15.150-1-MANJARO Machine: x86_64 Proc: 
2024-05-01 23:51:49.210 - INFO - separator - Python Version: 3.10.12
2024-05-01 23:51:49.210 - INFO - separator - PyTorch Version: 2.1.2+cu118
2024-05-01 23:51:49.281 - INFO - separator - FFmpeg installed: ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
2024-05-01 23:51:49.283 - INFO - separator - ONNX Runtime GPU package installed with version: 1.17.1
2024-05-01 23:51:49.284 - INFO - separator - ONNX Runtime CPU package installed with version: 1.16.3
2024-05-01 23:51:49.314 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-05-01 23:51:49.314 - INFO - separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
2024-05-01 23:51:49.314 - INFO - separator - Loading model htdemucs_ft.yaml...
2024-05-01 23:51:49.527 - INFO - demucs_separator - Demucs Separator initialisation complete
2024-05-01 23:51:49.527 - INFO - separator - Load model duration: 00:00:00
2024-05-01 23:51:49.527 - INFO - separator - Starting separation process for audio_file_path: audio_example.mp3
Traceback (most recent call last):
  File "/home/bingo06/miniconda3/envs/cu118/bin/audio-separator", line 8, in <module>
    sys.exit(main())
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/utils/cli.py", line 177, in main
    output_files = separator.separate(args.audio_file)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/separator.py", line 671, in separate
    output_files = self.model_instance.separate(audio_file_path)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/architectures/demucs_separator.py", line 104, in separate
    self.demucs_model_instance = get_demucs_model(name=os.path.splitext(os.path.basename(self.model_path))[0], repo=Path(os.path.dirname(self.model_path)))
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/pretrained.py", line 79, in get_model
    model = any_repo.get_model(name)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/repo.py", line 146, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/repo.py", line 127, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/repo.py", line 127, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/repo.py", line 97, in get_model
    check_checksum(file, self._checksums[sig])
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/audio_separator/separator/uvr_lib_v5/demucs/repo.py", line 39, in check_checksum
    raise ModelLoadingError(f"Invalid checksum for file {path}, " f"expected {checksum} but got {actual_checksum}")
audio_separator.separator.uvr_lib_v5.demucs.repo.ModelLoadingError: Invalid checksum for file /tmp/audio-separator-models/f7e0c4bc-ba3fe64a.th, expected ba3fe64a but got ef7153e5
```

```
(cu118) (cu118) [bingo06@zernithos ~]$ cd /tmp/audio-separator-models
(cu118) (cu118) [bingo06@zernithos audio-separator-models]$ ll
total 259396
drwxr-xr-x   2 bingo06 bingo06      160 May  1 23:46 .
drwxrwxrwt 185 root    root        5180 May  1 23:48 ..
-rw-r--r--   1 bingo06 bingo06 84141271 May  1 23:46 04573f0d-f3cf25b2.th
-rw-r--r--   1 bingo06 bingo06 84141271 May  1 23:46 92cfc3b6-ef3bcb9c.th
-rw-r--r--   1 bingo06 bingo06 84141271 May  1 23:45 d12395a8-e57c48e6.th
-rw-r--r--   1 bingo06 bingo06    17194 May  1 23:37 download_checks.json
-rw-r--r--   1 bingo06 bingo06 13164544 May  1 23:45 f7e0c4bc-ba3fe64a.th
-rw-r--r--   1 bingo06 bingo06      149 May  1 23:46 htdemucs_ft.yaml
```

**Comment by beveradb** [comment]
Looks like something got corrupted when your model files were being downloaded:

```
(separator) ➜  test-separator audio-separator test.flac --model_filename "htdemucs_ft.yaml"
2024-05-01 12:07:52.187 - INFO - cli - Separator version 0.16.6 beginning with input file: test.flac
2024-05-01 12:07:52.188 - INFO - separator - Separator version 0.16.6 instantiating with output_dir: None, output_format: FLAC
2024-05-01 12:07:52.188 - INFO - separator - Operating System: Darwin Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
2024-05-01 12:07:52.220 - INFO - separator - System: Darwin Node: VVN46RXL9Q Release: 23.4.0 Machine: arm64 Proc: arm
2024-05-01 12:07:52.221 - INFO - separator - Python Version: 3.12.3
2024-05-01 12:07:52.221 - INFO - separator - PyTorch Version: 2.3.0
2024-05-01 12:07:56.225 - INFO - separator - FFmpeg installed: ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
2024-05-01 12:07:56.227 - INFO - separator - ONNX Runtime CPU package installed with version: 1.17.3
2024-05-01 12:07:56.265 - INFO - separator - Apple Silicon MPS/CoreML is available in Torch, setting Torch device to MPS
2024-05-01 12:07:56.265 - INFO - separator - ONNXruntime has CoreMLExecutionProvider available, enabling acceleration
2024-05-01 12:07:56.265 - INFO - separator - Loading model htdemucs_ft.yaml...
17.2kiB [00:00, 12.0MiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84.1M/84.1M [00:02<00:00, 40.6MiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84.1M/84.1M [00:02<00:00, 42.0MiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84.1M/84.1M [00:01<00:00, 43.9MiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84.1M/84.1M [00:01<00:00, 45.0MiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [00:00<00:00, 97.3kiB/s]
2024-05-01 12:08:15.289 - INFO - demucs_separator - Demucs Separator initialisation complete
2024-05-01 12:08:15.289 - INFO - separator - Load model duration: 00:00:19
2024-05-01 12:08:15.289 - INFO - separator - Starting separation process for audio_file_path: test.flac
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:30<00:00,  1.42it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.48it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.45it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.49it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.50it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.48it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:17<00:00,  2.49it/s]
2024-05-01 12:10:58.108 - INFO - common_separator - Clearing input audio file paths, sources and stems...
2024-05-01 12:10:58.108 - INFO - separator - Separation duration: 00:02:42
2024-05-01 12:10:58.108 - INFO - cli - Separation complete! Output file(s): test_(Bass)_htdemucs_ft.flac test_(Drums)_htdemucs_ft.flac test_(Other)_htdemucs_ft.flac test_(Vocals)_htdemucs_ft.flac
```

```
(separator) ➜  test-separator ls -la /tmp/audio-separator-models
total 691776
drwxr-xr-x@  8 andrewbeveridge  wheel       256 May  1 12:08 .
drwxrwxrwt  26 root             wheel       832 May  1 12:08 ..
-rw-r--r--@  1 andrewbeveridge  wheel  84141271 May  1 12:08 04573f0d-f3cf25b2.th
-rw-r--r--@  1 andrewbeveridge  wheel  84141271 May  1 12:08 92cfc3b6-ef3bcb9c.th
-rw-r--r--@  1 andrewbeveridge  wheel  84141271 May  1 12:08 d12395a8-e57c48e6.th
-rw-r--r--@  1 andrewbeveridge  wheel     17194 May  1 12:07 download_checks.json
-rw-r--r--@  1 andrewbeveridge  wheel  84141271 May  1 12:07 f7e0c4bc-ba3fe64a.th
-rw-r--r--@  1 andrewbeveridge  wheel       149 May  1 12:08 htdemucs_ft.yaml
```

If you delete the model dir and run it again it should download again, you should be good after that 😄 

```
rm -rf /tmp/audio-separator-models
```
